### ISSUE TITLE
Add characters to the application

### ISSUE THREAD

**Issue by Brian-Kwong** [Brian-Kwong/Pawsitive-Studying#55]
Your goal for this application is to add characters to the application
Start by adding 3 endpoints to the backend : 
- Get all characters 
- Get all characters for a user (those who are in the user's character's array are unlocked)
- On the top of the screen display the current number of points available to the user (I will update the backend to allow fetching of that data)
- Allow user to "purchase" their characters and subtract the appropriate number of points 
Afterward, design the characters and then implement a simple display design the characters.  A simple flex-wrap is sufficient.  Make a view for each char then make a grid of all of them.
Make each character clickable.  Clicking on it brings up a popup asking do you want to purchase
If yea allows them to purchase and update the view appropriately

**Comment by jzaval17** [comment]
Great job on implementing the endpoints for character management. The code is well-structured and easy to follow. Consider adding more detailed comments in the code to explain the logic behind certain functions, especially in the purchasing logic
